### ISSUE TITLE
extractall() starts one subprocess per file

### ISSUE THREAD

**Issue by seirl** [markokr/rarfile#100]
This is very inefficient. Most (all?) backends support extracting the full rar at once.

**Comment by markokr** [comment]
True.  But supporting this approach would be in conflict with other priorities of rarfile.  The focus of rarfile is

1) Support direct access to RAR entries without extraction to disk, while also supporting several backends.
2) Support predictible behaviour for .extactone/.extractall over several backends.

The problem with just launching unrar/unar/bsdtar for extraction to disk is that all backends behave differently for complicated situations like:
* Dangerous or corrupt/weirdly encoded filenames.
* Unix symlink/hardlink.
* NTFS symlink/hardlink/junction/stream
* Extended attributes/timestamps/modes.

Current approach makes possible to give predictible although not fully-featured not fast behaviour with all backends.

If your main use-case is full extraction of archive to disk, you can just pick a archiver of your choice and launch it yourself.
