### ISSUE TITLE
[Windows] Unicode in file paths

### ISSUE THREAD

**Issue by seanegoodwin** [markokr/rarfile#15]
It seems there are some problems in dealing with with rar files contained under a path containing unicode characters in Windows. This is only when the path contains unicode, not the filename itself.

When trying to load such a rar file, I get the following error:

rarfile.RarWarning: Non-fatal error [1]: b'\r\nCannot read contents of C:\Regular path here\??\myrar.rar\r\nNo files to extract\r\n'

I've removed the real path and the filename. The '??' is the part of the path that contains unicode 

I suspect this is more of a Windows problem than a problem in the library, but if possible rarfile should account for this.

**Comment by HinTak** [comment]
Seems somewhat related to mine:
https://github.com/markokr/rarfile/issues/28

**Comment by markokr** [comment]
Python 3.6 switched from ANSI Windows APIs to UTF16 ones. If the bug still exist with Python 3.6+ please reopen.
