### ISSUE TITLE
Bad rar causes infinite loop in rarfile.py

### ISSUE THREAD

**Issue by chuncheng** [markokr/rarfile#19]
def _load_metadata(self, handle):
        """Load archive members metadata."""
	    rarinfo = self._read_header(handle)
        while rarinfo:
            if len(rarinfo.filename) == 0:
		        break
            self.filelist.append(rarinfo)
            self.NameToInfo[rarinfo.filename] = rarinfo
            self._process_current(handle, constants.RAR_SKIP)
            rarinfo = self._read_header(handle)

[badrar.zip](https://github.com/markokr/rarfile/files/160939/badrar.zip)

**Comment by markokr** [comment]
Cannto reproduce, and this is not a code from rarfile.py
```
$ ./dumprar.py -t -t 0.rar 
Archive: 0.rar
 --- 0.rar requires password ---
```
If problem is caused by rarfile API, please post code that reproduces the problem.

**Comment by chuncheng** [comment]
Submitted to the wrong project. Wasted your time.
