### ISSUE TITLE
Signing releases

### ISSUE THREAD

**Issue by hlef** [markokr/rarfile#24]
Hi,

I'm the Debian maintainer of the python-rarfile package.

For security reasons, it would be good if you could provide PGP/GPG signed release tarballs. Signature checks are automatically done by our packaging systems and help us to determine whether a new release is trustworthy or not before packaging it.

More informations are available [here](https://wiki.debian.org/Creating%20signed%20GitHub%20releases).

Thanks,
Hugo (hle)

**Comment by markokr** [comment]
Although good idea, it seems too complicated with current CI-based release flow.  Also as signatures were removed from PYPI - https://blog.pypi.org/posts/2023-05-23-removing-pgp/ - the benefits seem now very low.

Closing.
