### ISSUE TITLE
[Windows 10] unrar not found with some archives

### ISSUE THREAD

**Issue by XenHat** [markokr/rarfile#29]
Hello, I created a new issue following issue creep in #13 

I am trying to use rarfile on Windows 10.

On rarfile 2.8, running `rarfile.is_rarfile` on my package returns `false` due the package being a rar5 file.
I cannot seem to be able to create a rar4 package that can be detected as valid either.

After finding out that rarfile 2.8 does not support rar5, I compiled and installed the current repo (at time of writing, latest commit is pulling in #25)

with my newly build rarfile-3.0-xxx.egg, I can sucessfully read the file list and a file out of the archive using:
```
rf = rarfile.RarFile(myFileName)
    for f in rf.infolist():
        print(f.filename, f.file_size)
        if f.filename == 'samplefile.txt':
            print(rf.read(f))
```
However, I am unable to run `rarfile.extractall` on that same file:
```
in __extract_rar_archive
    rf.extractall(install_dir,extract)
  File "C:\Python27\lib\site-packages\rarfile-3.0-py2.7.egg\rarfile.py", line 811, in extractall
    self._extract(fnlist, path, pwd)
  File "C:\Python27\lib\site-packages\rarfile-3.0-py2.7.egg\rarfile.py", line 877, in _extract
    p = custom_popen(cmd)
  File "C:\Python27\lib\site-packages\rarfile-3.0-py2.7.egg\rarfile.py", line 2805, in custom_popen
    raise RarCannotExec("Unrar not installed? (rarfile.UNRAR_TOOL=%r)" % UNRAR_TOOL)
rarfile.RarCannotExec: Unrar not installed? (rarfile.UNRAR_TOOL='unrar')
```
both `rar` and `undar` binaries are in path, and I have tried the following:

- `rarfile.UNRAR_TOOL="rar"`
- `rarfile.UNRAR_TOOL="unrar"`
- `rarfile.UNRAR_TOOL="rar.exe"`
- `rarfile.UNRAR_TOOL="unrar.exe"`
- `rarfile.UNRAR_TOOL="C:\\Program Files\WinRAR\\UnRAR"`
- `rarfile.UNRAR_TOOL="C:\\Program Files\WinRAR\\UnRAR.exe"`
- `rarfile.UNRAR_TOOL="C:\Program Files\WinRAR\UnRAR"`
- `rarfile.UNRAR_TOOL="C:\Program Files\WinRAR\UnRAR.exe"`
- `rarfile.UNRAR_TOOL="C:/Program Files/WinRAR/UnRAR"`
- `rarfile.UNRAR_TOOL="/cygwin/c/Program Files/WinRAR/UnRAR"`
- `rarfile.UNRAR_TOOL="/cygwin/c/Program Files/WinRAR/UnRAR.exe"`

The list goes on...
Some additional output:
```
>ls "C:\Program Files\WinRAR\UnRAR.exe" -ls
396 -rwxr-xr-x 1 Xenhat Xenhat 401808 Aug 15 00:16 'C:\Program Files\WinRAR\UnRAR.exe'
>dir "C:\Program Files\WinRAR\UnRAR.exe"
 Directory of C:\Program Files\WinRAR

2016-08-14  11:16 PM           401,808 UnRAR.exe
               1 File(s)        401,808 bytes
               0 Dir(s)  118,082,936,832 bytes free

F:\devel>which rar
/cygdrive/c/Program Files/WinRAR/rar

F:\devel>which winrar
/cygdrive/c/Program Files/WinRAR/winrar

F:\devel>which unrar
/cygdrive/c/Program Files/WinRAR/unrar

F:\devel>unrar /? | head -n 4

UNRAR 5.40 x64 freeware      Copyright (c) 1993-2016 Alexander Roshal

Usage:     unrar <command> -<switch 1> -<switch N> <archive> <files...>
```
Currently, UnRAR.exe exists in 3 different locations included in PATH, and **in the current working folder** as well. I cannot come up with a reason why this doesn't work.

Some more information about my environment:
* Makes use of cygwin so path can sometimes be `/cygdrive/c/something/blah.exe`
* I have a working example for both `tarfile` and `zipfile`

Any help would be appreciated.

**update**
I have managed to extract a small package conform to my framework.
The problem appears to only happen on some archives, I have successfully extracted other archives with sizes anywhere between 300K and 118MB.
I am still trying to find what is special about this archive as it appears to refuse extracting it.

**Comment by markokr** [comment]
You need add debug print()-s custom_popen() to check what the actual error says.  It does not seem to be rarfile problem.
