### ISSUE TITLE
trailing slashes for "leaf" directories, usage of '\\'

### ISSUE THREAD

**Issue by h5rdly** [markokr/rarfile#31]
Hi,

I Wanted to ask regarding some parsing issues I'm having. 

On Windows, Zipfile listings look like this:
'Folder/Folder2/FILE'
'Folder/Folder2/EmptyFolder/'

With Rarfile it's:
u'Folder\\\Folder2\\\FILE'
u'Folder\\\Folder2\\\EmptyFolder'

This causes obstacles - 
1. With the lack of trailing slashes, I need extra info to know if FILE a file or a folder.
2. I would need to parse windows and linux rars differently, as well as rarfiles and zipfiles, gzipfiles etc.

Would it be possible to add trailing slashes to last-in-line folders, and/or use Python's generic platform agnostic '/' instead of '\\\\'? That would be awesome, as it would allow to utilize a single generic archive parsing.

Thanks.

**Comment by XenHat** [comment]
The option to use a different path separator already exists. Did you take a look at the documentation linked in the README file?
The option you are looking for is called `PATH_SEP`, see https://rarfile.readthedocs.io/en/latest/api.html#rarfile.PATH_SEP

**Comment by markokr** [comment]
Actually in rarfile 3.0 the default path_sep is '/' now.

But rarfile does not have any special handling for dirs, you are supposed to check mode.

Seems ZIP format stores final '/' in archive, while RAR does not.  Should rarfile append '/' to dirs?

**Comment by h5rdly** [comment]
@XenHat
I was not aware of rarfile.PATH_SEP = '/', thanks for the reference.

is_dir() isn't much use for traversing the archive, like in a file manager. One can get the dir info either way, but it's an extra check on every "leaf" folder, might add up on vast archives so it's a bit of a shame. Also not compatible with the Zipfile style.


@markokr
I'm obviously biased, but it would make parsing smooth, as it would just need the pathname to figure dirs from files.
Even looking at a listing, it's sometimes hard to tell if something like "THIS" or "notes" is a file or a directory.
The question is really, why not? :)

**Comment by XenHat** [comment]
> Seems ZIP format stores final '/' in archive, while RAR does not. Should rarfile append '/' to dirs?
Since the RARFile information says it tries to behave the same as zipfile as much as possible, I would say yes.

Footnote: I wonder if the lack of trailing slash would cause my odd problem with some archives  (#29 )since it tends to happen with archives with multiple subfolder levels (the most common example I have is libboost, which is huge, tree-wise)?
