### ISSUE TITLE
setpassword() fails incorrectly

### ISSUE THREAD

**Issue by Safihre** [markokr/rarfile#35]
We use the `zf.testrar()` to see if the user put the correct password for a job during downloading.
But for some archives the `zf.setpassword()` will fail with:
```
zf.setpassword(password)
*** BadRarFile: Bad count to header decrypt - wrong password?
```
Even though it's the correct password.

I can share a test RAR if you like?

**Comment by markokr** [comment]
Yes, please attach testcase

**Comment by Safihre** [comment]
This is the file: https://www.dropbox.com/s/odvhh1c9eaq3lpu/_o_kfjovHd5r46rj4jDP3yg72H.part01.rar?dl=1
This is the password: `THX[town.ag]AND[ssl-news.info]`

**Comment by markokr** [comment]
That was an ugly one...

Unfortunetely only way to fix it is to fall back to pure-python sha1.

Thank you for reporting it.

**Comment by Safihre** [comment]
Sorry me again, but I found another one that also doesn't work with the new version.
Same password, new file:
https://www.dropbox.com/s/38zwhawx09lagkv/3CRjdfierx7_AZTH2NPXl7BJoY.part01.rar?dl=1

**Comment by Safihre** [comment]
Seems I was wrong, it works just fine!
