### ISSUE TITLE
[Feature request]: Add unar support

### ISSUE THREAD

**Issue by luigino** [markokr/rarfile#36]
As per subject, unar is on feature parity with the nonfree unrar and it's available on most linux distributions.
See [http://unarchiver.c3.cx/commandline](http://unarchiver.c3.cx/commandline).

**Comment by markokr** [comment]
Fixed in master.  It indeed does have good RAR support.

**Comment by gene1wood** [comment]
Fixed in bd6fbfc96dac1f66854e6807b7cfd4b5825f3ad6
