### ISSUE TITLE
isdir() vs ZipInfo.is_dir()

### ISSUE THREAD

**Issue by radek00p** [markokr/rarfile#44]
Hello,

Would that be possible to improve zipfile-compatibility when it comes to 'isdir()' method?
In ZipInfo class the equivalent is 'is_dir()'.

Thank you.
radek

**Comment by rmspeers** [comment]
@markokr  would you merge a PR if I provided one to make this change?

**Comment by piskvorky** [comment]
Also bit by this.

The rarfile documentation says `The interface is made as zipfile-like as possible.`, so this was an unexpected surprise.

**Comment by piskvorky** [comment]
Gah, found one more: `ZipFile.open(pwd)` vs `RarFile.open(psw)` (subtly different name of the optional password parameter).

**Comment by piskvorky** [comment]
@markokr is the `pwd` / `psw` resolved as well? Thanks.
