### ISSUE TITLE
BadRarFile, when header reads b"Rar!\x1a\x07\x01"

### ISSUE THREAD

**Issue by cubinator** [markokr/rarfile#46]
Password protected archives seem to include some more header information. If the archive header reads `b"Rar!\x1a\x07\x01"` instead of `b"Rar!\x1a\x07\x00"` (HEAD_SIZE is 0x0107 instead of 0x0007), the module raises `BadRarFile("Not a Rar archive: <filename>")`. I tried replacing `RAR_ID=b"Rar!\x1a\x07\x01"` with `RAR_ID=b"Rar!\x1a\x07"`, but then `rarfile.RarFile.infolist` always returns an empty list (didn't forget to set password).

**Comment by vslinuxdotnet** [comment]
I confirm this bug in RAR5 files the bytes are: Rar!\x1a\x07\x01 and RAR4 are: Rar!\x1a\x07\x00
I try to change to Rar!\x1a\x07\x01 and the rar validation passes but no file list.
Could be the address of the header list.

**Comment by markokr** [comment]
That is right signature for RAR5, please upgrade to newer rarfile that has rar5 support.
