### ISSUE TITLE
Error 193 when trying to read a RAR archive

### ISSUE THREAD

**Issue by roydbtR** [markokr/rarfile#50]
This is my code:

```
import rarfile
# Set to full path of unrar.exe if it is not in PATH
rarfile.UNRAR_TOOL = "C:\Python27\Lib\site-packages\unrar\unrarlib.py"

rf=rarfile.RarFile('unzipme.0')
for f in rf.infolist():
    print f.filename, f.file_size
    if f.filename == 'Boring':
        print true
```

And this is the output:

> Traceback (most recent call last):
>  File "C:/Users/*UserName*/Desktop/archives/__file.py", line 5, in <module>
>    rf=rarfile.RarFile('unzipme.0')
>  File "C:\Python27\lib\site-packages\rarfile.py", line 666, in __init__
>    self._parse()
>  File "C:\Python27\lib\site-packages\rarfile.py", line 858, in _parse
>    self._file_parser.parse()
>  File "C:\Python27\lib\site-packages\rarfile.py", line 973, in parse
>    self._parse_real()
>  File "C:\Python27\lib\site-packages\rarfile.py", line 1047, in _parse_real
>    self.process_entry(fd, h)
>  File "C:\Python27\lib\site-packages\rarfile.py", line 1460, in process_entry
>    cmt = self._read_comment_v3(item, self._password)
>  File "C:\Python27\lib\site-packages\rarfile.py", line 1414, in _read_comment_v3
>    inf.file_size, inf.flags, inf.CRC, psw, inf.salt)
>  File "C:\Python27\lib\site-packages\rarfile.py", line 2747, in rar3_decompress
>    p = custom_popen(cmd)
>  File "C:\Python27\lib\site-packages\rarfile.py", line 2813, in custom_popen
>    creationflags=creationflags)
>  File "C:\Python27\lib\subprocess.py", line 711, in __init__
>    errread, errwrite)
>  File "C:\Python27\lib\subprocess.py", line 959, in _execute_child
>    startupinfo)
>WindowsError: [Error 193] %1 is not a valid Win32 application

**Comment by markokr** [comment]
Instead unrarlib.py you should have unrar.exe there.
