### ISSUE TITLE
Cannot get the fp=rarfile.RarFile('test.rar')  object  when test.rar  is encrypted with filename.

### ISSUE THREAD

**Issue by hyq5890** [markokr/rarfile#54]

**Comment by hyq5890** [comment]
fp = rarfile.RarFile(filenameDec)

Is ususlly ok.
But,when "filenameDec"  is encrypted with filename.  It seems get into infinite loop when load the object fp.

What can I do ?

**Comment by markokr** [comment]
I don't get what "encrypted with filename" is, could you give code example?
