### ISSUE TITLE
Include Rar3 volume number 

### ISSUE THREAD

**Issue by Safihre** [markokr/rarfile#58]
We (me and @sanderjo) were very happy to see your activity here again!
And now you also added a way to actually retrieve the volume number from Rar5 files. 
Could you implement the same for Rar3? It would be very useful for our application where we have to deal with obfuscated Rar files and detect which ones belong together.

We now have our own custom code, but would be great if we could use Rarfile for everything! We already use it in a number of different locations in our application. 
https://github.com/sabnzbd/sabnzbd/commit/a5c8318b5fdaae4521651e0881522fbe3deeb154

**Comment by markokr** [comment]
Unfortunately RAR3 does not contain such info, so cannot implement it.

**Comment by sanderjo** [comment]
> Unfortunately RAR3 does not contain such info, so cannot implement it.

Did you see https://github.com/sabnzbd/sabnzbd/commit/a5c8318b5fdaae4521651e0881522fbe3deeb154#diff-13c4161154ee8c590e1c06c8cbc3da8dR20-R24 ?

**Comment by markokr** [comment]
Aha, I missed it then.  Its problably endarc-volnr, which we dont parse yet.  But indeed we should.

**Comment by markokr** [comment]
Please see if it works for you now.
