### ISSUE TITLE
Some tests fail with python 3.6.5

### ISSUE THREAD

**Issue by lgbaldoni** [markokr/rarfile#62]
On openSUSE Leap 15.1.
Unsure if the python version is the actual culprit, everything works with 3.6.10 and 3.8.x.

Anyway here's the [log](https://github.com/markokr/rarfile/files/5034952/rarfile4_leap151.txt).

**Comment by markokr** [comment]
Seems 3.6.5 has trouble with unicode filenames.  I cannot see how rarfile could work around that.

If you are building a package, then simplest would be to disable the tests.  Or better, backport the filename fix for python...

**Comment by lgbaldoni** [comment]
Thanks, I'll follow your suggestion.
