### ISSUE TITLE
`custom_check` function removed in version 3.2 but release notes don't mention it

### ISSUE THREAD

**Issue by gene1wood** [markokr/rarfile#70]
It looks like the `custom_check` function [was removed](https://github.com/markokr/rarfile/commit/bd6fbfc96dac1f66854e6807b7cfd4b5825f3ad6#diff-6f65689dbef41b40b2428db20aefd2bd3738967d6ad03314e8a61eec3d754604L2850-L2857) in bd6fbfc96dac1f66854e6807b7cfd4b5825f3ad6 as part of the [v3.2](https://github.com/markokr/rarfile/releases/tag/v3.2) release.

You may want to add to the release notes that this function isn't present anymore, maybe in the Cleanups section and mention it as a potentially breaking change. I discovered this in Diaoul/subliminal#1013 which [uses the `custom_check` function](https://github.com/Diaoul/subliminal/blob/a4113adb745dc5cd2da7254ee14802077237bb15/subliminal/providers/legendastv.py#L164).

**Comment by markokr** [comment]
Yeah, seems it was oversight when doing release notes.

**Comment by gene1wood** [comment]
@markokr 
You may want to add to the release notes that this function isn't present anymore, maybe in the Cleanups section and mention it as a potentially breaking change. I discovered this in Diaoul/subliminal#1013 which [uses the `custom_check` function](https://github.com/Diaoul/subliminal/blob/a4113adb745dc5cd2da7254ee14802077237bb15/subliminal/providers/legendastv.py#L164).

**Comment by markokr** [comment]
It's possible 3.x is still around, so it's better to add it just in case.

Thanks.
