### ISSUE TITLE
Add 7z to the fallback chain for supported unarchivers

### ISSUE THREAD

**Issue by ssokolow** [markokr/rarfile#71]
If you're supporting extracting RAR files using `unar`, it'd probably also be a good idea to support falling back to p7zip's `7z` command.

It has RAR support with the `p7zip-rar` package (or equivalent) installed (which is in the repositories of various Debian-family distros and listed as a `Suggests` dependency for `p7zip-full` which is, itself, a `Suggests` depdendency for `p7zip`),  and is more likely to be installed than The Unarchiver for a variety of reasons.

(eg. If you search for how to unpack `.7z` files on Linux, you'll be led to it, People moving from Windows to Linux who know 7-Zip are much more common than people moving from macOS to Linux who know The Unarchiver, etc.)

I've been installing `p7zip-rar` since I switched to Ubuntu-family distros about a decade ago, but I only learned of The Unarchiver's command-line tools relatively recently when `lsar -t` turned up in searches for how to verify the integrity of old Stuffit archives on Linux before I move them to DVD+Rs of retro-computing supplies. (And "Yes, you can do it. Here's how." wasn't exactly the top result either.)

Heck, just now, I looked at `bsdtar` in your list of supported commands and, with a very puzzled look on my face, thought "Really? `bsdtar` can handle RAR archives? Why?" before I looked at the URL and said "Ohh... It's based on libarchive... libarchive handles RAR archives?"

I suspect anyone with experience with 7-Zip on Windows will have similar intuitive expectations, given how 7-Zip has supplanted WinRAR as the no-cost "installed on every computer and opens anything" tool for the Windows ecosystem.

Oh, and just to make sure there's no misunderstanding if you've seen my [ssokolow/rar-test-files](https://github.com/ssokolow/rar-test-files) repository, when I mentioned `7z` as a reason to integration-test with both RAR3 and RAR5 test files, that's *specifically* the ancient 9.02 version from 2009 included with long-term support releases like Ubuntu 16.04 LTS. The 16.02 version from 2016 that's included with Ubuntu 20.04 LTS handles RAR5 files just fine. (And `7z t` reports no problems with any of the test archives in that repository.)

**Comment by markokr** [comment]
I would be happy to add 7z as backend, the problem is that is does not have "decompress to stdout" option which is critical for `rarfile`.  unrar-free has same problem - https://gitlab.com/bgermann/unrar-free/

This usage is supported by `unrar`, `bsdtar` and `unar`, so they are usable as `rarfile` backend.
