### ISSUE TITLE
'NoneType' object is not iterable

### ISSUE THREAD

**Issue by HDmonsterShen** [markokr/rarfile#75]
when I open a RAR file with password:
`rf = rarfile.RarFile('D:\\test_file.rar',mode="r")`
`rf.setpassword(pwd='123456'`
`rf.extractall('D:\\')`
`rf.close()`
i got a error
'NoneType' object is not iterable'

this is all the error information:

Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/Code/StruggleSky/tool/main.py", line 6, in <module>
    rf.extractall('D:\\',pwd='123456')
  File "C:\ProgramData\Anaconda3\lib\site-packages\rarfile.py", line 847, in extractall
    dst = self._extract_one(inf, path, pwd, not inf.is_dir())
  File "C:\ProgramData\Anaconda3\lib\site-packages\rarfile.py", line 912, in _extract_one
    return self._make_file(info, dstfn, pwd, set_attrs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\rarfile.py", line 925, in _make_file
    with self.open(info, "r", pwd) as src:
  File "C:\ProgramData\Anaconda3\lib\site-packages\rarfile.py", line 783, in open
    return self._file_parser.open(inf, pwd)
  File "C:\ProgramData\Anaconda3\lib\site-packages\rarfile.py", line 1241, in open
    return self._open_unrar(self._rarfile, inf, pwd)
  File "C:\ProgramData\Anaconda3\lib\site-packages\rarfile.py", line 1294, in _open_unrar
    cmd = setup.open_cmdline(pwd, rarfile, fn)
  File "C:\ProgramData\Anaconda3\lib\site-packages\rarfile.py", line 3235, in open_cmdline
    cmdline = self.get_cmdline("open_cmd", pwd)
  File "C:\ProgramData\Anaconda3\lib\site-packages\rarfile.py", line 3247, in get_cmdline
    self.add_password_arg(cmdline, pwd)
  File "C:\ProgramData\Anaconda3\lib\site-packages\rarfile.py", line 3266, in add_password_arg
    cmdline.extend(args)
TypeError: 'NoneType' object is not iterable

**Comment by majidaldo** [comment]
This was tiggered b/c the unraring executable is bsdtar. When I checked my executable there was no option to decrypt a passworded archive.
```
bsdtar: manipulate archive files
First option must be a mode specifier:
  -c Create  -r Add/Replace  -t List  -u Update  -x Extract
Common Options:
  -b #  Use # 512-byte records per I/O block
  -f <filename>  Location of archive (default \\.\tape0)
  -v    Verbose
  -w    Interactive
Create: bsdtar -c [options] [<file> | <dir> | @<archive> | -C <dir> ]
  <file>, <dir>  add these items to archive
  -z, -j, -J, --lzma  Compress archive with gzip/bzip2/xz/lzma
  --format {ustar|pax|cpio|shar}  Select archive format
  --exclude <pattern>  Skip files that match pattern
  -C <dir>  Change to <dir> before processing remaining files
  @<archive>  Add entries from <archive> to output
List: bsdtar -t [options] [<patterns>]
  <patterns>  If specified, list only entries that match
Extract: bsdtar -x [options] [<patterns>]
  <patterns>  If specified, extract only entries that match
  -k    Keep (don't overwrite) existing files
  -m    Don't restore modification times
  -O    Write entries to stdout, don't restore to disk
  -p    Restore permissions (including ACLs, owner, file flags)
bsdtar 3.5.2 - libarchive 3.5.2 zlib/1.2.11 liblzma/5.2.5 bz2lib/1.0.8 liblz4/1.9.3 libzstd/1.5.0
```

**Comment by majidaldo** [comment]
..so then i started to use the 'unrar' executable. However, there's still a problem! For some reason, the unrar exec wants the fn fwd slashed!! So I added the appropriate platform-agnostic fix.

You can patch it as follows:
```
import rarfile
def open_cmdline(self, pwd, rarfn, filefn=None):
    cmdline = self.get_cmdline("open_cmd", pwd)
    cmdline.append(rarfn)
    if filefn:
        from pathlib import Path                                # added
        self.add_file_arg(cmdline, str(Path(filefn)) )    # chenged
    return cmdline
rarfile.ToolSetup.open_cmdline = open_cmdline
```

**Comment by HDmonsterShen** [comment]
i use your method:
import os
import rarfile
def open_cmdline(self, pwd, rarfn, filefn=None):
    cmdline = self.get_cmdline("open_cmd", pwd)
    cmdline.append(rarfn)
    if filefn:
        from pathlib import Path                                # added
        self.add_file_arg(cmdline, str(Path(filefn)) )    # chenged
    return cmdline
rarfile.ToolSetup.open_cmdline = open_cmdline

rf = rarfile.RarFile('D:\\test\\test.rar',mode='r')
# rf.setpassword(pwd='123456')
rf.extractall(path="D:\\",pwd="123456")
rf.close()

it`s still something was wrong
>>>:{'open_cmd': ('BSDTAR_TOOL', '-x', '--to-stdout', '-f'), 'check_cmd': ('BSDTAR_TOOL', '--version'), 'password': None, 'no_password': (), 'errmap': [None]}
>>> TypeError:
TypeError                                 Traceback (most recent call last)
<ipython-input-20-6bde3ac7bf04> in <module>
      1 rf = rarfile.RarFile('D:\\新建文件夹\\2020epub.rar',mode='r')
      2 # rf.setpassword(pwd='123456')
----> 3 rf.extractall(path="D:\\",pwd="123456")
      4 rf.close()

C:\ProgramData\Anaconda3\lib\site-packages\rarfile.py in extractall(self, path, members, pwd)
    845         for m in members:
    846             inf = self.getinfo(m)
--> 847             dst = self._extract_one(inf, path, pwd, not inf.is_dir())
    848             if inf.is_dir():
    849                 if dst not in done:

C:\ProgramData\Anaconda3\lib\site-packages\rarfile.py in _extract_one(self, info, path, pwd, set_attrs)
    910 
    911         if info.is_file():
--> 912             return self._make_file(info, dstfn, pwd, set_attrs)
    913         if info.is_dir():
    914             return self._make_dir(info, dstfn, pwd, set_attrs)

C:\ProgramData\Anaconda3\lib\site-packages\rarfile.py in _make_file(self, info, dstfn, pwd, set_attrs)
    923         def helper(name, flags):
    924             return self._create_helper(name, flags, info)
--> 925         with self.open(info, "r", pwd) as src:
    926             with open(dstfn, "wb", opener=helper) as dst:
    927                 shutil.copyfileobj(src, dst)

C:\ProgramData\Anaconda3\lib\site-packages\rarfile.py in open(self, name, mode, pwd)
    781             pwd = None
    782 
--> 783         return self._file_parser.open(inf, pwd)
    784 
    785     def read(self, name, pwd=None):

C:\ProgramData\Anaconda3\lib\site-packages\rarfile.py in open(self, inf, pwd)
   1239             return self._open_unrar_membuf(self._rarfile, inf, pwd)
   1240         else:
-> 1241             return self._open_unrar(self._rarfile, inf, pwd)
   1242 
   1243     def _open_clear(self, inf):

C:\ProgramData\Anaconda3\lib\site-packages\rarfile.py in _open_unrar(self, rarfile, inf, pwd, tmpfile, force_file)
   1292 
   1293         # read from unrar pipe
-> 1294         cmd = setup.open_cmdline(pwd, rarfile, fn)
   1295         return PipeReader(self, inf, cmd, tmpfile)
   1296 

<ipython-input-13-95410b42fe9a> in open_cmdline(self, pwd, rarfn, filefn)
      3 import rarfile
      4 def open_cmdline(self, pwd, rarfn, filefn=None):
----> 5     cmdline = self.get_cmdline("open_cmd", pwd)
      6     cmdline.append(rarfn)
      7     if filefn:

C:\ProgramData\Anaconda3\lib\site-packages\rarfile.py in get_cmdline(self, key, pwd, nodash)
   3245         cmdline = list(self.setup[key])
   3246         cmdline[0] = globals()[cmdline[0]]
-> 3247         self.add_password_arg(cmdline, pwd)
   3248         if not nodash:
   3249             cmdline.append("--")

C:\ProgramData\Anaconda3\lib\site-packages\rarfile.py in add_password_arg(self, cmdline, pwd)
   3264                 cmdline.append(args + pwd)
   3265             else:
-> 3266                 cmdline.extend(args)
   3267                 cmdline.append(pwd)
   3268         else:

TypeError: 'NoneType' object is not iterable

**Comment by majidaldo** [comment]
> collback:{'open_cmd': ('BSDTAR_TOOL', '-x', '--to-stdout', '-f'), 'check_cmd': ('BSDTAR_TOOL', '--version'), 'password': None, 'no_password': (), 'errmap': [None]}

are you sure you have 'unrar' in your PATH? for windows i got it from https://www.rarlab.com/rar/unrarw32.exe

**Comment by 2597miles** [comment]
I got the same issue and it makes me crazy!
