### ISSUE TITLE
Rar2 Support

### ISSUE THREAD

**Issue by MontraTV** [markokr/rarfile#82]
Is there a possibility to add rar2 support? I have a bunch of files that need to be rar2 format to work properly.

**Comment by markokr** [comment]
rar 2.x and 3.x should be compatible format-wise, so it should work already?

If there are problem, please provide sample files to test on.

**Comment by markokr** [comment]
Closing: rarfile is already tested with both rar 2.0 and rar 1.5 archives, so they should mostly work.

If there is problem with specific archive, please provide testcase.
