### ISSUE TITLE
Unable to extract RAR file in AWS Glue

### ISSUE THREAD

**Issue by Ketan0493** [markokr/rarfile#84]
Hi,

I am working on an AWS glue job(spark shell) in which i am downloading a RAR file from web source and then trying to exxtrat it in S# bucket.
I am using rarfile module to extract, but getting below error:
**Cannot find a working tool**
i tried installing unrar on my linux container, but still facing the same issue.

Hope if you could help!!

Thanks,
Ketan Sharma

**Comment by markokr** [comment]
The `unrar` command must be in PATH also, then `rarfile` can find it.
