### ISSUE TITLE
serious disadvantage： When the rar file contains multiple directories, it cannot be decompressed and the data in the file can be read

### ISSUE THREAD

**Issue by 906827215** [markokr/rarfile#88]
When the data format is as follows, everything is normal：
![image](https://user-images.githubusercontent.com/24824256/181181945-ba2e12d2-9a30-4854-8b28-cfe7ec405ea8.png)
When the data has a directory:
![image](https://user-images.githubusercontent.com/24824256/181182155-254a394f-523b-417f-9431-fbebf1b9e32c.png)
![image](https://user-images.githubusercontent.com/24824256/181182794-fcd76aa4-139d-4b08-94ed-89bb0361784b.png)

![image](https://user-images.githubusercontent.com/24824256/181182480-019228b5-af32-40c4-869a-34d3570ac95a.png)
I have tried many times. When there is no directory layer, everything is normal. When I have a directory layer, I will always tell me the above error. This is beyond my comprehension, so I ask for help

**Comment by 906827215** [comment]
I just want to say that when there is a layer of directory in front of the last CSV, it cannot be decompressed and read with code. The following figure is used to illustrate the part I express

![image](https://user-images.githubusercontent.com/24824256/181183778-900a4a37-7b59-4ddc-8831-8faaa986441d.png)
![image](https://user-images.githubusercontent.com/24824256/181183844-3e6587ad-546d-4c2a-a0c3-fffa9964226c.png)

**Comment by 906827215** [comment]
When there is no directory layer in front of CSV, it can be read and decompressed smoothly

He has a good result

![1658905987425](https://user-images.githubusercontent.com/24824256/181184795-67299062-7b8c-45ed-8765-0f0ece7a9166.jpg)

**Comment by markokr** [comment]
Thank you for excellent report.  The problem should be fixed by PR #96 that just got merged.
