### ISSUE TITLE
rarfile unar unsupported on Windows

### ISSUE THREAD

**Issue by adrianAnyansi** [markokr/rarfile#90]
More of a disclaimer than issue since unrar should be used but:
rarfile's implementation is decompressed files are first piped to stdout, bytes read from Popen(cmd) then returned via .read(name) or written to file via .extract(name).

unar has the restriction that a fileHandler must be passed via -o and as far as I know, it's impossible to pass stdout as a parameter on Windows. This causes the non-descriptive error where you get something like `rarfile.BadRarFile: Failed the read enough data: req=454392 got=166` cause the data/buffer is empty but an object exists.

Either rarfile can use a temp directory or raise an error preventing a Windows user from using unar.

**Comment by markokr** [comment]
Last unar windows build is from 2013 - v1.8.1 - that does not support output to stdout.

Adding version checkong to code seems too much complexity for this, I think its simpler to clearly document what tools are supported.
