### ISSUE TITLE
BSDTAR_TOOL does not support passwords

### ISSUE THREAD

**Issue by edocono** [markokr/rarfile#92]
I tried to extract a .rar file which contains a .mat file. After correcting my script with the newest version that I found here in github, I have now this problem. My file is obviously protected by a password, and I don't understand why the function does not use the unrar tool instead of the BSDTAR tool to extract my file,
The scripts that I'm using are the following:
import rarfile
rf= rarfile.RarFile('filename.rar')
rf.extract(member='filename.mat', pwd="password")

import rarfile
with rarfile.RarFile('filename.rar') as rf:
    rf.extract(member='filename.mat', pwd='password')

**Comment by markokr** [comment]
bsdtar uses libarchive which does not support RAR passwords, so it is expected that it does not work.

unrar must be in PATH, or you can assign rarfile.UNRAR_TOOL to full path to unrar executable.
