### ISSUE TITLE
unrar-free support

### ISSUE THREAD

**Issue by MichaIng** [markokr/rarfile#94]
On several Linux distributions, a free variant of `unrar` is provided, e.g. on Debian:
- https://packages.debian.org/unrar-free
- https://manpages.debian.org/unrar-free

It provides the `unrar` command and, as can be seen on the manual page, has certain compatibility with the CLI of the non-free variant.

However, `rarfile.py` uses the `-inul` flag to "disable all messages" when using the `unrar` command, which is not understood by the free variant.

As processing output is usually omitted with STDOUT not being a console, and informational+error messages can be actually useful, compared to omitting them, I wonder whether this is needed. Omitting `-inul` should enable `unrar-free` support.

**Comment by markokr** [comment]
unrar-free does not support output to stdout, thus it is not usable as rarfile backend.

**Comment by MichaIng** [comment]
Ah right, then there is no way around `unar` as free alternative. Thanks for looking into it.

**Comment by bgermann** [comment]
unrar-free Version 0.2.0 Supports printing to stdout.

**Comment by MichaIng** [comment]
Debian is not able to detect the new upstream versions: https://tracker.debian.org/pkg/unrar-free

The pattern matches, but GitLab has the link embedded in some weird encoding, which probably causes issues:
```console
# curl -sSfL 'https://gitlab.com/bgermann/unrar-free/tags?sort=updated_desc' | grep -Pm1 'archive/(?:[-_]?[Vv]?(\d[\-+\.:\~\da-zA-Z]*))/unrar-free-\d\S*\.tar\.gz'
<div class="js-source-code-dropdown" data-css-class="" data-download-artifacts="[]" data-download-links="[{&quot;text&quot;:&quot;zip&quot;,&quot;path&quot;:&quot;/bgermann/unrar-free/-/archive/0.3.0/unrar-free-0.3.0.zip&quot;},{&quot;text&quot;:&quot;tar.gz&quot;,&quot;path&quot;:&quot;/bgermann/unrar-free/-/archive/0.3.0/unrar-free-0.3.0.tar.gz&quot;},{&quot;text&quot;:&quot;tar.bz2&quot;,&quot;path&quot;:&quot;/bgermann/unrar-free/-/archive/0.3.0/unrar-free-0.3.0.tar.bz2&quot;},{&quot;text&quot;:&quot;tar&quot;,&quot;path&quot;:&quot;/bgermann/unrar-free/-/archive/0.3.0/unrar-free-0.3.0.tar&quot;}]"></div>
```

**Comment by bgermann** [comment]
I have worked with the package maintainer in the past and already notified him about the new version. Eventually, the package will get updated. I will make sure that it will until the trixie trelease.
