### ISSUE TITLE
rarfile.BadRarFile: Failed the read enough data: req=65536 got=51

### ISSUE THREAD

**Issue by dv000-7** [markokr/rarfile#95]
Hello,
i am using python 3.10 

importing rarfile to extract files.
if i am installing rar and unrar  code works fine.

but somehow i dont want to use rar and unrar
then i am getting the error 
raise BadRarFile("Failed the read enough data: req=%d got=%d" % (orig, len(data)))
rarfile.BadRarFile: Failed the read enough data: req=65536 got=51

anyone can help me or suggest any other library which should work without using rar and unrar.
Thanks

**Comment by markokr** [comment]
You can use either unar or bsdtar as decompressor if you dont want to use unrar.  Without backend tool, rarfile can extract only uncompressed files from archives.
